services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "bd"
      MYSQL_DATABASE: "bd"
      MYSQL_USER: "bd"
      MYSQL_PASSWORD: "bd"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
